services:
  fastapi:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: zenn-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ARTICLE_DIR=${ARTICLE_DIR:-./articles}
      - GITHUB_PAT=$(GITHUB_PA)
      - GITHUB_USER=$(GITHUB_USER)
      - USER_NAME=$(USER_NAME)
      - USER_EMAIL=$(USER_EMAIL)

volumes:
  ollama:
