services:
  fastapi:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: zenn-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - ollama
    environment:
      - KENN_ZENN_URL=${KENN_ZENN_URL}
      - OLLAMA_URL=${OLLAMA_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  ollama:
    image: ollama/ollama
    container_name: zenn-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
